services:
  store.app:
    image: store.app
    build:
      context: .
      dockerfile: Store.App/Dockerfile
    depends_on:
      Database:
        condition: service_healthy
    networks:
      - store_network
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__IdentityDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=identity
      - ConnectionStrings__CatalogDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=catalog
      - ConnectionStrings__CartDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=cart
      - ConnectionStrings__OrderingDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=ordering
      - ConnectionStrings__InventoryDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=inventory
      - JwtOptions__SecretKey=${JWT_SECRET_KEY}
      - JwtOptions__Issuer=${JWT_ISSUER}
      - JwtOptions__Audience=${JWT_AUDIENCE}
  
  Database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: Store
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - store_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Store"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  store_network:

volumes:
  database_volume: