services:
  store.app:
    image: store.app
    build:
      context: .
      dockerfile: Store.App/Dockerfile
    depends_on:
      - Database
    networks:
      - store_network
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***
      - ConnectionStrings__IdentityDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=identity
      - ConnectionStrings__CatalogDbConnectionString=Host=Database;Database=Store;Username=postgres;Password=***;SearchPath=catalog
  
  Database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: Store
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - store_network
    ports:
      - "5432:5432"

networks:
  store_network:

volumes:
  database_volume: