// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Store.Inventory.Infrastructure.DbContexts;

#nullable disable

namespace Store.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Store.EventOutbox.Infrastructure.Entity.DomainEventOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeadLettered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ProcessedOnUtc", "IsDeadLettered", "NextAttemptOnUtc");

                    b.ToTable("domain_event_outbox", "inventory");
                });

            modelBuilder.Entity("Store.EventOutbox.Infrastructure.Entity.ProcessedDomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Consumer")
                        .IsUnique();

                    b.ToTable("processed_domain_events", "inventory");
                });

            modelBuilder.Entity("Store.Inventory.Infrastructure.Entity.StockItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("StockItems", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_StockItems_ProductId_NotEmpty", "\"ProductId\" <> '00000000-0000-0000-0000-000000000000'");
                            t.HasCheckConstraint("CK_StockItems_Quantity_NonNegative", "\"Quantity\" >= 0");
                            t.HasCheckConstraint("CK_StockItems_Reserved_NonNegative", "\"Reserved\" >= 0");
                            t.HasCheckConstraint("CK_StockItems_Reserved_NotGreaterThanQuantity", "\"Reserved\" <= \"Quantity\"");
                        });
                });

            modelBuilder.Entity("Store.Inventory.Infrastructure.Entity.StockReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId", "OrderId")
                        .IsUnique();

                    b.ToTable("StockReservations", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_StockReservations_OrderId_NotEmpty", "\"OrderId\" <> '00000000-0000-0000-0000-000000000000'");
                            t.HasCheckConstraint("CK_StockReservations_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Store.Inventory.Infrastructure.Entity.StockReservationEntity", b =>
                {
                    b.HasOne("Store.Inventory.Infrastructure.Entity.StockItemEntity", "StockItem")
                        .WithMany("Reservations")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Store.Inventory.Infrastructure.Entity.StockItemEntity", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
