<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.104.2" />
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Store.App\Store.App.csproj" />
        <ProjectReference Include="..\Store.Carts\Store.Carts.csproj" />
        <ProjectReference Include="..\Store.Catalog\Store.Catalog.csproj" />
        <ProjectReference Include="..\Store.Consulting\Store.Consulting.csproj" />
        <ProjectReference Include="..\Store.Identity\Store.Identity.csproj" />
        <ProjectReference Include="..\Store.Inventory\Store.Inventory.csproj" />
        <ProjectReference Include="..\Store.Notifications\Store.Notifications.csproj" />
        <ProjectReference Include="..\Store.Ordering\Store.Ordering.csproj" />
    </ItemGroup>

</Project>
