name: dotnet

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        working-directory: backend
        run: dotnet restore Store.sln --disable-parallel

      - name: Build
        working-directory: backend
        run: dotnet build Store.sln --configuration Release --no-restore -maxcpucount:1

      - name: Test
        working-directory: backend
        run: dotnet test Store.sln --configuration Release --no-build -maxcpucount:1 --verbosity normal
